### ISSUE TITLE
Typestyle with glimmerjs

### ISSUE THREAD

**Issue by collegeimprovements** [typestyle/typestyle#167]
Hi, I'm sure it's my lack of understanding, but how can i make it work with glimmerjs.
Glimmerjs uses typescript and have component and template file in it.

Here is an example:
------------
### component.ts file
```typescript
import Component from "@glimmer/component";
import { style } from "typestyle";

export default class AboutRoute extends Component {
  redColor = style({ color: "red" });
}
```

and 

### template.hbs file
```html
<div>
  <h1 class="{{redColor}}">About Route</h1>
</div>

### Full Error Stack
```
------------
I tried the above approach but it didn't work. It doesn't apply the redColor class 
I know I'm doing something obviously wrong. It's giving the following error:
`Error loading node_modules/typestyle/lib.es2015/types.js: plugin load hook should return a string, a { code, map } object, or nothing/null`.
```
The Broccoli Plugin: [BroccoliMergeTrees] failed with:
Error: Error loading node_modules/typestyle/lib.es2015/types.js: plugin load hook should return a string, a { code, map } object, or nothing/null
    at error (/Users/shaha/Desktop/clsa-it/node_modules/rollup/dist/rollup.js:170:12)
    at /Users/shaha/Desktop/clsa-it/node_modules/rollup/dist/rollup.js:9468:4

The broccoli plugin was instantiated at:
    at BroccoliMergeTrees.Plugin (/Users/shaha/Desktop/clsa-it/node_modules/broccoli-plugin/index.js:7:31)
    at new BroccoliMergeTrees (/Users/shaha/Desktop/clsa-it/node_modules/@glimmer/application-pipeline/node_modules/broccoli-merge-trees/index.js:16:10)
    at GlimmerApp.package (/Users/shaha/Desktop/clsa-it/node_modules/@glimmer/application-pipeline/dist/lib/broccoli/glimmer-app.js:240:23)
    at GlimmerApp.toTree (/Users/shaha/Desktop/clsa-it/node_modules/@glimmer/application-pipeline/dist/lib/broccoli/glimmer-app.js:271:28)
    at module.exports (/Users/shaha/Desktop/clsa-it/ember-cli-build.js:14:14)
    at Builder.setupBroccoliBuilder (/Users/shaha/Desktop/clsa-it/node_modules/ember-cli/lib/models/builder.js:56:19)
    at new Builder (/Users/shaha/Desktop/clsa-it/node_modules/ember-cli/lib/models/builder.js:30:10)
    at ServeTask.run (/Users/shaha/Desktop/clsa-it/node_modules/ember-cli/lib/tasks/serve.js:24:55)
    at Promise.resolve.then (/Users/shaha/Desktop/clsa-it/node_modules/ember-cli/lib/models/command.js:243:46)
    at tryCatch (/Users/shaha/Desktop/clsa-it/node_modules/rsvp/dist/rsvp.js:525:12)
```
Can you help me here!!

**Comment by notoriousb1t** [comment]
This appears to be a misconfiguration of rollup or the file it is trying to import is not present.  I don't know how to help you with this, unfortunately. 

According to the docs, there is an ```@tracked``` annotation that you could try, but I don't see why you would need to do that.

**Comment by basarat** [comment]
> This appears to be a misconfiguration of rollup or the file it is trying to import is not present

Agreed. The `types.js` file is because it is just the type annotation file https://github.com/typestyle/typestyle/blob/a411297a484148b954eb9db0c296d8927c5a20ea/src/types.ts that exists so that a `types.d.ts` file is generated for the output. 

The contents of `types.js`  is : 

```
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
```

Some tool in the chain (not TypeScript and not TypeStyle) is misconfigured. I empathise with you, but the issue really belongs elsewhere :rose:
